[build]
  # Build command
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

  # Directory to publish (your built frontend)
  publish = "dist"

  # Tell Netlify where your serverless functions live
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# ---------- SPA Redirects ----------
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/shopkeeper/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/salesman/*"
  to = "/index.html"
  status = 200

# ---------- API Redirects ----------
# This maps /api/... to your function names
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ---------- Security Headers ----------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# ---------- CORS Headers for API ----------
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
